const unidades = {
  GRAMAS: 'gramas (g)',
  QUILOGRAMAS: 'quilogramas (kg)',
  COPO: 'copo',
  XICARA: 'xícara',
  XICARA_CHA: 'xícara de chá',
  COLHER: 'colher',
  COLHER_SOPA: 'colher de sopa',
  COLHER_CHA: 'colher de chá',
  COLHER_CAFE: 'colher de café',
  COLHER_SOBREMESA: 'colher de sobremesa',
  FATIA: 'fatia',
  UNIDADE: 'unidade',
  ITEM: 'item',
  FILE: 'filé',
  BIFE: 'bife',
  PORCAO: 'porção',
  DENTE: 'dente',
  TABLETE: 'tablete',
  MACO: 'maço',
  CONCHA: 'concha',
  PRATO: 'prato',
};

module.exports = unidades;
